# Generated by Django 5.2.7 on 2025-10-22 20:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name="address",
            old_name="isDefault",
            new_name="is_default",
        ),
        migrations.RenameField(
            model_name="serviceproviderprofile",
            old_name="total_ratings",
            new_name="total_rating",
        ),
    ]
