# Generated by Django 5.1.4 on 2024-12-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_tasklog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklog",
            old_name="details",
            new_name="data_details",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="error_message",
            new_name="message",
        ),
    ]
