# Generated by Django 5.1.4 on 2025-01-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_rename_details_tasklog_data_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklog",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="tasklog",
            name="is_deleted",
        ),
    ]
