# Generated by Django 5.1.4 on 2025-03-22 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_tasklog_is_active_remove_tasklog_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("4dd11b35-fc89-4bbe-9895-7ec771b9fb29"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
