# Generated by Django 5.1.4 on 2025-03-22 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_tasklog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("167ba614-5339-442b-91bf-62a663686c6f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
