# Generated by Django 5.1.4 on 2025-03-22 21:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_tasklog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
